INSERT INTO songs (title, album, artist, image_url) VALUES ('Something in the Orange', 'American Heartbreak', 'Zach Bryan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Maine', 'Busyhead', 'Noah Kahan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Lonely Island', 'Lonely Island', 'Amble', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Stick Season', 'Stick Season', 'Noah Kahan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Northern Attitude', 'Stick Season', 'Noah Kahan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Dial Drunk', 'Stick Season', 'Noah Kahan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Heading South', 'Heading South', 'Zach Bryan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Oklahoma Smokeshow', 'American Heartbreak', 'Zach Bryan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Revival', 'American Heartbreak', 'Zach Bryan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Burn, Burn, Burn', 'American Heartbreak', 'Zach Bryan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('The Night We Met', 'Strange Trails', 'Lord Huron', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Ends of the Earth', 'Lonesome Dreams', 'Lord Huron', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Meet Me in the Woods', 'Strange Trails', 'Lord Huron', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('All My Love', 'Stick Season (Forever)', 'Noah Kahan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Growing Sideways', 'Stick Season', 'Noah Kahan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Orange Juice', 'Stick Season', 'Noah Kahan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Forever', 'Stick Season (Forever)', 'Noah Kahan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Take Me Home, Country Roads', 'Poems, Prayers & Promises', 'John Denver', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Wagon Wheel', 'True Believers', 'Darius Rucker', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Feathered Indians', 'Purgatory', 'Tyler Childers', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Lady May', 'Purgatory', 'Tyler Childers', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Whitehouse Road', 'Purgatory', 'Tyler Childers', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Coal', 'Coal', 'Dylan Gossett', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Beneath Oak Trees', 'No Better Time', 'Dylan Gossett', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Evergreen', 'RMCM', 'Richy Mitch & The Coal Miners', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Lake Missoula', 'Colorado''s On Fire Again', 'Richy Mitch & The Coal Miners', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Pink Skies', 'The Great American Bar Scene', 'Zach Bryan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('I Remember Everything', 'Zach Bryan', 'Zach Bryan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Sun to Me', 'American Heartbreak', 'Zach Bryan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Tennessee Whiskey', 'Traveller', 'Chris Stapleton', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Starting Over', 'Starting Over', 'Chris Stapleton', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Broken Halos', 'From A Room: Volume 1', 'Chris Stapleton', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Dust in a Baggie', 'Turmoil & Tinfoil', 'Billy Strings', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Away From the Mire', 'Home', 'Billy Strings', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Cover Me Up', 'Southeastern', 'Jason Isbell', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('If We Were Vampires', 'The Nashville Sound', 'Jason Isbell and the 400 Unit', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Sleeping on the Blacktop', 'Imaginary Appalachia', 'Colter Wall', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('The Devil Wears a Suit and Tie', 'Colter Wall', 'Colter Wall', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('The Stable Song', 'This Empty Northern Hemisphere', 'Gregory Alan Isakov', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Big Black Car', 'The Weatherman', 'Gregory Alan Isakov', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('San Luis', 'Evening Machines', 'Gregory Alan Isakov', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Cherry Wine', 'Hozier', 'Hozier', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Work Song', 'Hozier', 'Hozier', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('From Austin', 'American Heartbreak', 'Zach Bryan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('East Side of Sorrow', 'Zach Bryan', 'Zach Bryan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('68 Fastback', 'American Heartbreak', 'Zach Bryan', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Take Me Back to Eden', 'Take Me Back to Eden', 'Sleep Token', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Euclid', 'Take Me Back to Eden', 'Sleep Token', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Like Real People Do', 'Hozier', 'Hozier', '');
INSERT INTO songs (title, album, artist, image_url) VALUES ('Unknown / Nth', 'Unreal Unearth', 'Hozier', '');