INSERT INTO songs (name, artist, date_added, notes) VALUES ('Something in the Orange', 'Zach Bryan', '2026-03-17', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Maine', 'Noah Kahan', '2025-09-04', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Lonely Island', 'Amble', '2026-01-28', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Stick Season', 'Noah Kahan', '2025-11-13', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Northern Attitude', 'Noah Kahan', '2025-07-22', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Dial Drunk', 'Noah Kahan', '2026-05-09', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Heading South', 'Zach Bryan', '2025-08-15', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Oklahoma Smokeshow', 'Zach Bryan', '2026-04-21', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Revival', 'Zach Bryan', '2025-12-06', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Burn, Burn, Burn', 'Zach Bryan', '2025-10-30', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('The Night We Met', 'Lord Huron', '2026-02-11', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Ends of the Earth', 'Lord Huron', '2025-06-29', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Meet Me in the Woods', 'Lord Huron', '2026-06-01', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('All My Love', 'Noah Kahan', '2025-08-27', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Growing Sideways', 'Noah Kahan', '2026-01-05', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Orange Juice', 'Noah Kahan', '2025-11-25', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Forever', 'Noah Kahan', '2025-07-11', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Take Me Home, Country Roads', 'John Denver', '2026-04-04', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Wagon Wheel', 'Darius Rucker', '2025-12-18', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Feathered Indians', 'Tyler Childers', '2025-09-20', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Lady May', 'Tyler Childers', '2026-02-24', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Whitehouse Road', 'Tyler Childers', '2025-10-08', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Coal', 'Dylan Gossett', '2026-03-02', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Beneath Oak Trees', 'Dylan Gossett', '2025-08-02', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Evergreen', 'Richy Mitch & The Coal Miners', '2026-05-22', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Lake Missoula', 'Richy Mitch & The Coal Miners', '2025-11-02', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Pink Skies', 'Zach Bryan', '2026-01-14', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('I Remember Everything', 'Zach Bryan', '2025-09-28', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Sun to Me', 'Zach Bryan', '2026-04-28', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Tennessee Whiskey', 'Chris Stapleton', '2025-07-05', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Starting Over', 'Chris Stapleton', '2026-02-03', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Broken Halos', 'Chris Stapleton', '2025-10-16', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Dust in a Baggie', 'Billy Strings', '2026-05-15', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Away From the Mire', 'Billy Strings', '2025-08-21', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Cover Me Up', 'Jason Isbell', '2026-03-29', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('If We Were Vampires', 'Jason Isbell and the 400 Unit', '2025-12-29', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Sleeping on the Blacktop', 'Colter Wall', '2025-07-30', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('The Devil Wears a Suit and Tie', 'Colter Wall', '2026-04-13', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('The Stable Song', 'Gregory Alan Isakov', '2025-11-20', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Big Black Car', 'Gregory Alan Isakov', '2026-01-20', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('San Luis', 'Gregory Alan Isakov', '2025-09-11', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Cherry Wine', 'Hozier', '2026-05-03', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Work Song', 'Hozier', '2025-08-09', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('From Austin', 'Zach Bryan', '2026-02-16', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('East Side of Sorrow', 'Zach Bryan', '2025-10-24', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('68 Fastback', 'Zach Bryan', '2026-03-11', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Take Me Back to Eden', 'Sleep Token', '2025-07-17', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Euclid', 'Sleep Token', '2026-06-12', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Like Real People Do', 'Hozier', '2025-12-12', '');
INSERT INTO songs (name, artist, date_added, notes) VALUES ('Unknown / Nth', 'Hozier', '2026-04-18', '');
INSERT INTO song_links (song_id, link) VALUES (1, '');
INSERT INTO song_links (song_id, link) VALUES (1, '');
INSERT INTO song_links (song_id, link) VALUES (2, '');
INSERT INTO song_links (song_id, link) VALUES (2, '');
INSERT INTO song_links (song_id, link) VALUES (3, '');
INSERT INTO song_links (song_id, link) VALUES (3, '');
INSERT INTO song_links (song_id, link) VALUES (4, '');
INSERT INTO song_links (song_id, link) VALUES (4, '');
INSERT INTO song_links (song_id, link) VALUES (5, '');
INSERT INTO song_links (song_id, link) VALUES (5, '');
INSERT INTO song_links (song_id, link) VALUES (6, '');
INSERT INTO song_links (song_id, link) VALUES (6, '');
INSERT INTO song_links (song_id, link) VALUES (7, '');
INSERT INTO song_links (song_id, link) VALUES (7, '');
INSERT INTO song_links (song_id, link) VALUES (8, '');
INSERT INTO song_links (song_id, link) VALUES (8, '');
INSERT INTO song_links (song_id, link) VALUES (9, '');
INSERT INTO song_links (song_id, link) VALUES (9, '');
INSERT INTO song_links (song_id, link) VALUES (10, '');
INSERT INTO song_links (song_id, link) VALUES (10, '');
INSERT INTO song_links (song_id, link) VALUES (11, '');
INSERT INTO song_links (song_id, link) VALUES (11, '');
INSERT INTO song_links (song_id, link) VALUES (12, '');
INSERT INTO song_links (song_id, link) VALUES (12, '');
INSERT INTO song_links (song_id, link) VALUES (13, '');
INSERT INTO song_links (song_id, link) VALUES (13, '');
INSERT INTO song_links (song_id, link) VALUES (14, '');
INSERT INTO song_links (song_id, link) VALUES (14, '');
INSERT INTO song_links (song_id, link) VALUES (15, '');
INSERT INTO song_links (song_id, link) VALUES (15, '');
INSERT INTO song_links (song_id, link) VALUES (16, '');
INSERT INTO song_links (song_id, link) VALUES (16, '');
INSERT INTO song_links (song_id, link) VALUES (17, '');
INSERT INTO song_links (song_id, link) VALUES (17, '');
INSERT INTO song_links (song_id, link) VALUES (18, '');
INSERT INTO song_links (song_id, link) VALUES (18, '');
INSERT INTO song_links (song_id, link) VALUES (19, '');
INSERT INTO song_links (song_id, link) VALUES (19, '');
INSERT INTO song_links (song_id, link) VALUES (20, '');
INSERT INTO song_links (song_id, link) VALUES (20, '');
INSERT INTO song_links (song_id, link) VALUES (21, '');
INSERT INTO song_links (song_id, link) VALUES (21, '');
INSERT INTO song_links (song_id, link) VALUES (22, '');
INSERT INTO song_links (song_id, link) VALUES (22, '');
INSERT INTO song_links (song_id, link) VALUES (23, '');
INSERT INTO song_links (song_id, link) VALUES (23, '');
INSERT INTO song_links (song_id, link) VALUES (24, '');
INSERT INTO song_links (song_id, link) VALUES (24, '');
INSERT INTO song_links (song_id, link) VALUES (25, '');
INSERT INTO song_links (song_id, link) VALUES (25, '');
INSERT INTO song_links (song_id, link) VALUES (26, '');
INSERT INTO song_links (song_id, link) VALUES (26, '');
INSERT INTO song_links (song_id, link) VALUES (27, '');
INSERT INTO song_links (song_id, link) VALUES (27, '');
INSERT INTO song_links (song_id, link) VALUES (28, '');
INSERT INTO song_links (song_id, link) VALUES (28, '');
INSERT INTO song_links (song_id, link) VALUES (29, '');
INSERT INTO song_links (song_id, link) VALUES (29, '');
INSERT INTO song_links (song_id, link) VALUES (30, '');
INSERT INTO song_links (song_id, link) VALUES (30, '');
INSERT INTO song_links (song_id, link) VALUES (31, '');
INSERT INTO song_links (song_id, link) VALUES (31, '');
INSERT INTO song_links (song_id, link) VALUES (32, '');
INSERT INTO song_links (song_id, link) VALUES (32, '');
INSERT INTO song_links (song_id, link) VALUES (33, '');
INSERT INTO song_links (song_id, link) VALUES (33, '');
INSERT INTO song_links (song_id, link) VALUES (34, '');
INSERT INTO song_links (song_id, link) VALUES (34, '');
INSERT INTO song_links (song_id, link) VALUES (35, '');
INSERT INTO song_links (song_id, link) VALUES (35, '');
INSERT INTO song_links (song_id, link) VALUES (36, '');
INSERT INTO song_links (song_id, link) VALUES (36, '');
INSERT INTO song_links (song_id, link) VALUES (37, '');
INSERT INTO song_links (song_id, link) VALUES (37, '');
INSERT INTO song_links (song_id, link) VALUES (38, '');
INSERT INTO song_links (song_id, link) VALUES (38, '');
INSERT INTO song_links (song_id, link) VALUES (39, '');
INSERT INTO song_links (song_id, link) VALUES (39, '');
INSERT INTO song_links (song_id, link) VALUES (40, '');
INSERT INTO song_links (song_id, link) VALUES (40, '');
INSERT INTO song_links (song_id, link) VALUES (41, '');
INSERT INTO song_links (song_id, link) VALUES (41, '');
INSERT INTO song_links (song_id, link) VALUES (42, '');
INSERT INTO song_links (song_id, link) VALUES (42, '');
INSERT INTO song_links (song_id, link) VALUES (43, '');
INSERT INTO song_links (song_id, link) VALUES (43, '');
INSERT INTO song_links (song_id, link) VALUES (44, '');
INSERT INTO song_links (song_id, link) VALUES (44, '');
INSERT INTO song_links (song_id, link) VALUES (45, '');
INSERT INTO song_links (song_id, link) VALUES (45, '');
INSERT INTO song_links (song_id, link) VALUES (46, '');
INSERT INTO song_links (song_id, link) VALUES (46, '');
INSERT INTO song_links (song_id, link) VALUES (47, '');
INSERT INTO song_links (song_id, link) VALUES (47, '');
INSERT INTO song_links (song_id, link) VALUES (48, '');
INSERT INTO song_links (song_id, link) VALUES (48, '');
INSERT INTO song_links (song_id, link) VALUES (49, '');
INSERT INTO song_links (song_id, link) VALUES (49, '');
INSERT INTO song_links (song_id, link) VALUES (50, '');
INSERT INTO song_links (song_id, link) VALUES (50, '');