INSERT INTO songs (id, name, artist, date_added, notes) VALUES (1, 'Something in the Orange', 'Zach Bryan', '2026-03-17', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (2, 'Maine', 'Noah Kahan', '2025-09-04', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (3, 'Lonely Island', 'Amble', '2026-01-28', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (4, 'Stick Season', 'Noah Kahan', '2025-11-13', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (5, 'Northern Attitude', 'Noah Kahan', '2025-07-22', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (6, 'Dial Drunk', 'Noah Kahan', '2026-05-09', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (7, 'Heading South', 'Zach Bryan', '2025-08-15', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (8, 'Oklahoma Smokeshow', 'Zach Bryan', '2026-04-21', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (9, 'Revival', 'Zach Bryan', '2025-12-06', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (10, 'Burn, Burn, Burn', 'Zach Bryan', '2025-10-30', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (11, 'The Night We Met', 'Lord Huron', '2026-02-11', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (12, 'Ends of the Earth', 'Lord Huron', '2025-06-29', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (13, 'Meet Me in the Woods', 'Lord Huron', '2026-06-01', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (14, 'All My Love', 'Noah Kahan', '2025-08-27', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (15, 'Growing Sideways', 'Noah Kahan', '2026-01-05', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (16, 'Orange Juice', 'Noah Kahan', '2025-11-25', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (17, 'Forever', 'Noah Kahan', '2025-07-11', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (18, 'Take Me Home, Country Roads', 'John Denver', '2026-04-04', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (19, 'Wagon Wheel', 'Darius Rucker', '2025-12-18', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (20, 'Feathered Indians', 'Tyler Childers', '2025-09-20', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (21, 'Lady May', 'Tyler Childers', '2026-02-24', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (22, 'Whitehouse Road', 'Tyler Childers', '2025-10-08', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (23, 'Coal', 'Dylan Gossett', '2026-03-02', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (24, 'Beneath Oak Trees', 'Dylan Gossett', '2025-08-02', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (25, 'Evergreen', 'Richy Mitch & The Coal Miners', '2026-05-22', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (26, 'Lake Missoula', 'Richy Mitch & The Coal Miners', '2025-11-02', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (27, 'Pink Skies', 'Zach Bryan', '2026-01-14', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (28, 'I Remember Everything', 'Zach Bryan', '2025-09-28', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (29, 'Sun to Me', 'Zach Bryan', '2026-04-28', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (30, 'Tennessee Whiskey', 'Chris Stapleton', '2025-07-05', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (31, 'Starting Over', 'Chris Stapleton', '2026-02-03', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (32, 'Broken Halos', 'Chris Stapleton', '2025-10-16', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (33, 'Dust in a Baggie', 'Billy Strings', '2026-05-15', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (34, 'Away From the Mire', 'Billy Strings', '2025-08-21', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (35, 'Cover Me Up', 'Jason Isbell', '2026-03-29', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (36, 'If We Were Vampires', 'Jason Isbell and the 400 Unit', '2025-12-29', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (37, 'Sleeping on the Blacktop', 'Colter Wall', '2025-07-30', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (38, 'The Devil Wears a Suit and Tie', 'Colter Wall', '2026-04-13', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (39, 'The Stable Song', 'Gregory Alan Isakov', '2025-11-20', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (40, 'Big Black Car', 'Gregory Alan Isakov', '2026-01-20', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (41, 'San Luis', 'Gregory Alan Isakov', '2025-09-11', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (42, 'Cherry Wine', 'Hozier', '2026-05-03', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (43, 'Work Song', 'Hozier', '2025-08-09', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (44, 'From Austin', 'Zach Bryan', '2026-02-16', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (45, 'East Side of Sorrow', 'Zach Bryan', '2025-10-24', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (46, '68 Fastback', 'Zach Bryan', '2026-03-11', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (47, 'Take Me Back to Eden', 'Sleep Token', '2025-07-17', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (48, 'Euclid', 'Sleep Token', '2026-06-12', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (49, 'Like Real People Do', 'Hozier', '2025-12-12', '');
INSERT INTO songs (id, name, artist, date_added, notes) VALUES (50, 'Unknown / Nth', 'Hozier', '2026-04-18', '');
INSERT INTO song_links (song_id, link) VALUES (1, '');
INSERT INTO song_links (song_id, link) VALUES (1, '');
INSERT INTO song_links (song_id, link) VALUES (2, '');
INSERT INTO song_links (song_id, link) VALUES (2, '');
INSERT INTO song_links (song_id, link) VALUES (3, '');
INSERT INTO song_links (song_id, link) VALUES (3, '');
INSERT INTO song_links (song_id, link) VALUES (4, '');
INSERT INTO song_links (song_id, link) VALUES (4, '');
INSERT INTO song_links (song_id, link) VALUES (5, '');
INSERT INTO song_links (song_id, link) VALUES (5, '');
INSERT INTO song_links (song_id, link) VALUES (6, '');
INSERT INTO song_links (song_id, link) VALUES (6, '');
INSERT INTO song_links (song_id, link) VALUES (7, '');
INSERT INTO song_links (song_id, link) VALUES (7, '');
INSERT INTO song_links (song_id, link) VALUES (8, '');
INSERT INTO song_links (song_id, link) VALUES (8, '');
INSERT INTO song_links (song_id, link) VALUES (9, '');
INSERT INTO song_links (song_id, link) VALUES (9, '');
INSERT INTO song_links (song_id, link) VALUES (10, '');
INSERT INTO song_links (song_id, link) VALUES (10, '');
INSERT INTO song_links (song_id, link) VALUES (11, '');
INSERT INTO song_links (song_id, link) VALUES (11, '');
INSERT INTO song_links (song_id, link) VALUES (12, '');
INSERT INTO song_links (song_id, link) VALUES (12, '');
INSERT INTO song_links (song_id, link) VALUES (13, '');
INSERT INTO song_links (song_id, link) VALUES (13, '');
INSERT INTO song_links (song_id, link) VALUES (14, '');
INSERT INTO song_links (song_id, link) VALUES (14, '');
INSERT INTO song_links (song_id, link) VALUES (15, '');
INSERT INTO song_links (song_id, link) VALUES (15, '');
INSERT INTO song_links (song_id, link) VALUES (16, '');
INSERT INTO song_links (song_id, link) VALUES (16, '');
INSERT INTO song_links (song_id, link) VALUES (17, '');
INSERT INTO song_links (song_id, link) VALUES (17, '');
INSERT INTO song_links (song_id, link) VALUES (18, '');
INSERT INTO song_links (song_id, link) VALUES (18, '');
INSERT INTO song_links (song_id, link) VALUES (19, '');
INSERT INTO song_links (song_id, link) VALUES (19, '');
INSERT INTO song_links (song_id, link) VALUES (20, '');
INSERT INTO song_links (song_id, link) VALUES (20, '');
INSERT INTO song_links (song_id, link) VALUES (21, '');
INSERT INTO song_links (song_id, link) VALUES (21, '');
INSERT INTO song_links (song_id, link) VALUES (22, '');
INSERT INTO song_links (song_id, link) VALUES (22, '');
INSERT INTO song_links (song_id, link) VALUES (23, '');
INSERT INTO song_links (song_id, link) VALUES (23, '');
INSERT INTO song_links (song_id, link) VALUES (24, '');
INSERT INTO song_links (song_id, link) VALUES (24, '');
INSERT INTO song_links (song_id, link) VALUES (25, '');
INSERT INTO song_links (song_id, link) VALUES (25, '');
INSERT INTO song_links (song_id, link) VALUES (26, '');
INSERT INTO song_links (song_id, link) VALUES (26, '');
INSERT INTO song_links (song_id, link) VALUES (27, '');
INSERT INTO song_links (song_id, link) VALUES (27, '');
INSERT INTO song_links (song_id, link) VALUES (28, '');
INSERT INTO song_links (song_id, link) VALUES (28, '');
INSERT INTO song_links (song_id, link) VALUES (29, '');
INSERT INTO song_links (song_id, link) VALUES (29, '');
INSERT INTO song_links (song_id, link) VALUES (30, '');
INSERT INTO song_links (song_id, link) VALUES (30, '');
INSERT INTO song_links (song_id, link) VALUES (31, '');
INSERT INTO song_links (song_id, link) VALUES (31, '');
INSERT INTO song_links (song_id, link) VALUES (32, '');
INSERT INTO song_links (song_id, link) VALUES (32, '');
INSERT INTO song_links (song_id, link) VALUES (33, '');
INSERT INTO song_links (song_id, link) VALUES (33, '');
INSERT INTO song_links (song_id, link) VALUES (34, '');
INSERT INTO song_links (song_id, link) VALUES (34, '');
INSERT INTO song_links (song_id, link) VALUES (35, '');
INSERT INTO song_links (song_id, link) VALUES (35, '');
INSERT INTO song_links (song_id, link) VALUES (36, '');
INSERT INTO song_links (song_id, link) VALUES (36, '');
INSERT INTO song_links (song_id, link) VALUES (37, '');
INSERT INTO song_links (song_id, link) VALUES (37, '');
INSERT INTO song_links (song_id, link) VALUES (38, '');
INSERT INTO song_links (song_id, link) VALUES (38, '');
INSERT INTO song_links (song_id, link) VALUES (39, '');
INSERT INTO song_links (song_id, link) VALUES (39, '');
INSERT INTO song_links (song_id, link) VALUES (40, '');
INSERT INTO song_links (song_id, link) VALUES (40, '');
INSERT INTO song_links (song_id, link) VALUES (41, '');
INSERT INTO song_links (song_id, link) VALUES (41, '');
INSERT INTO song_links (song_id, link) VALUES (42, '');
INSERT INTO song_links (song_id, link) VALUES (42, '');
INSERT INTO song_links (song_id, link) VALUES (43, '');
INSERT INTO song_links (song_id, link) VALUES (43, '');
INSERT INTO song_links (song_id, link) VALUES (44, '');
INSERT INTO song_links (song_id, link) VALUES (44, '');
INSERT INTO song_links (song_id, link) VALUES (45, '');
INSERT INTO song_links (song_id, link) VALUES (45, '');
INSERT INTO song_links (song_id, link) VALUES (46, '');
INSERT INTO song_links (song_id, link) VALUES (46, '');
INSERT INTO song_links (song_id, link) VALUES (47, '');
INSERT INTO song_links (song_id, link) VALUES (47, '');
INSERT INTO song_links (song_id, link) VALUES (48, '');
INSERT INTO song_links (song_id, link) VALUES (48, '');
INSERT INTO song_links (song_id, link) VALUES (49, '');
INSERT INTO song_links (song_id, link) VALUES (49, '');
INSERT INTO song_links (song_id, link) VALUES (50, '');
INSERT INTO song_links (song_id, link) VALUES (50, '');